import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export default function TermsOfService() {
    return (
        <div className="min-h-screen bg-black text-white p-8 md:p-16">
            <div className="max-w-4xl mx-auto space-y-8">
                <Link href="/" className="flex items-center gap-2 text-gray-400 hover:text-white transition w-fit">
                    <ArrowLeft className="w-4 h-4" /> Back to Home
                </Link>

                <h1 className="text-4xl font-bold bg-gradient-to-r from-purple-400 to-pink-600 bg-clip-text text-transparent">
                    Terms of Service
                </h1>
                <p className="text-gray-400">Last updated: {new Date().toLocaleDateString()}</p>

                <div className="space-y-6 text-gray-300 leading-relaxed">
                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-2">1. Acceptance of Terms</h2>
                        <p>By accessing and using J.A.R.A ("the Application"), you accept and agree to be bound by the terms and provision of this agreement.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-2">2. Description of Service</h2>
                        <p>J.A.R.A is an AI-powered job assistant that helps users manage their job search process, including resume analysis and application tracking. We provide automation tools to assist you, but we guarantee no specific employment outcomes.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-2">3. User Responsibilities</h2>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>You are responsible for maintaining the confidentiality of your account and password.</li>
                            <li>You agree to provide true, accurate, current, and complete information about yourself.</li>
                            <li>You agree not to use the service for any illegal or unauthorized purpose.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-2">4. AI and Automation Disclaimer</h2>
                        <p>Our service uses Artificial Intelligence to analyze data and automate tasks. While we strive for accuracy, AI systems can make mistakes. You should always review important applications or communications generated by the system before sending.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-2">5. Termination</h2>
                        <p>We reserve the right to terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-2">6. Changes to Terms</h2>
                        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. What constitutes a material change will be determined at our sole discretion.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-2">7. Contact Us</h2>
                        <p>If you have any questions about these Terms, please contact us at support@jara.ai.</p>
                    </section>
                </div>
            </div>
        </div>
    );
}
